parameters:
    report_filename.station_1: '%kernel.project_dir%/data/station_one_report.csv'
    report_filename.station_2: '%kernel.project_dir%/data/station_two_report.json'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    report_sources.station_1:
        class: App\Source\FileSource
        arguments: ['%report_filename.station_1%']

    report_sources.station_2:
        class: App\Source\FileSource
        arguments: ['%report_filename.station_2%']

    report_provider.station_1:
        class: App\Provider\WeatherStationReportProvider
        arguments: [1, '@report_sources.station_1', '@App\Decoder\CsvDecoder', '@App\Transformer\TypeOneDataTransformer']
        tags: ['app.report_provider']

    report_provider.station_2:
        class: App\Provider\WeatherStationReportProvider
        arguments: [2, '@report_sources.station_2', '@App\Decoder\JsonDecoder', '@App\Transformer\TypeTwoDataTransformer']
        tags: ['app.report_provider']

    App\Repository\WeatherStationReportProviderRepository:
        arguments:
            - !tagged_iterator 'app.report_provider'